### ISSUE TITLE
https

### ISSUE THREAD

**Issue by dohliam** [IonicaBizau/CaiuSS#10]
The `@import` line [at the beginning of the file](https://github.com/IonicaBizau/CaiuSS/blob/master/less/css/caiuss.less#L1) should be changed from `http://` to `https://`. I mention this because I noticed that importing OpenSans was blocked when I used CaiuSS on a site served over https (i.e., [mixed content error](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content)).

**Comment by IonicaBizau** [comment]
Good point! 👍 Can you do it? I'd be happy to merge it!

**Comment by dohliam** [comment]
Done! An easy fix. :smile:
